// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqskjwbukzswqfqdczre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxc2tqd2J1a3pzd3FmcWRjenJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Njk2MjEsImV4cCI6MjA2NzU0NTYyMX0.al5QS_HGK5tGhhytbVkkh6-J8mdN0DjE-bzNEbAXLCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});